### ISSUE TITLE
Cannot complete "PI to 41 characters" challenge

### ISSUE THREAD

**Issue by Artemas-Muzanenhamo** [Keyma-sh/game-tracker#10]
**Describe the bug**
I cannot complete the "PI to 41 characters" challenge as it won't allow me to type the last few digits of the PI number shown.

**To Reproduce**
1. Go to 'Learn'
2. Click on 'INTRODUCTION TO NUMBERS'
3. Select 'PI TO 40 CHARACTERS'
4. Start typing the number on the screen.
5. You will see that you cannot type the numbers `8841971` at the end.

**Expected behavior**
To be able to type those numbers `8841971` and complete the challenge and move on to the next challenge.

**Screenshots**
<img width="1257" alt="PI-To-41-Characters-Bug" src="https://user-images.githubusercontent.com/29547780/117273539-22d80380-ae54-11eb-898d-fc21ba8471a0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Browser: Chrome
 - Version: 90.0.4430.93

**Comment by CameronCT** [comment]
Ah yes, this is definitely a bug.

By default we cap the input box’s max length to avoid major forms or copy pasting (not that it would work anyways). I’ll push a hotfix later tonight that will uncap the input for the learning area.

Thanks!

**Comment by CameronCT** [comment]
Update: Hotfix should be later tonight, I didn't have time for last night. :(

**Comment by CameronCT** [comment]
Cancel that, fix has been pushed.
