### ISSUE TITLE
Learn Center Improvements

### ISSUE THREAD

**Issue by SomethingTerrible666** [Keyma-sh/game-tracker#100]
I'm always frustrated when [1. The keyboard viewer, when I type in the dvorak layout I don't have much speed or muscle memory so the keyboard viewer is very distracting because my eyes are constantly drawn to it and I make mistakes.]

I'm always frustrated when [2. I get less than an "A" I get frustrated and do something else.]

I'm always frustrated when [3. You don't actually learn in the Learn Center you just practice combinations and simple words. I would've learned the dvorak layout in the "dvorak" Lessons but they don't offer enough to actually learn it from there.

**Describe the solution you'd like**
1. A toggle button to open or close Keyboard viewer

2. A percentage rating system for individual lessons or star system might be less discouraging and make people use it more.

3. Lessons that actually teach you the placements of each letter and then following lessons that have you practice words with the letters you just learned.

**Describe alternatives you've considered**
1. Customizable size adjustment for keyboard viewer.

2. Less punishing towards accuracy and having lessons instead that focus on accuracy eg. A required accuracy to continue. Instead of a "trouble keys" mode like typing.com which contains a lot of bogus words that are just hard to type having something like to https://www.keybr.com/help.

3. A required speed on common combinations of letters instead of slowly typing it. eg. tion east etc. Drawbacks. This might lead to an inconsistency in your typing speed.

**Additional context** Rewarding Achievements for completing certain tasks in the Learn center.
Learn Center can just be grinded in a day and you have no reason to return. Something like keybr would be nice.

**Comment by CameronCT** [comment]
Thanks for this post, right now we're actually considering removing the Learning Center as a whole and replacing it with more of a "resourceful" area where we can guide typists to areas where they can properly learn how to type either regularly or in a different keyboard layout (such as DVORAK/COLEMAK).

**Comment by CameronCT** [comment]
The vote is pretty unanimous to remove Learning, so we have. Therefore this issue has no reason to be opened.
