### ISSUE TITLE
Coin logo placement inconsistencies.

### ISSUE THREAD

**Issue by SomethingTerrible666** [Keyma-sh/game-tracker#101]
**Describe the bug**
Inconsistency: After obtaining 100K coins my coin logo went above my coin count instead of to the side like normally. Aevi's Coin logo never moved after obtaining 100K coins tho. Resolution didn't seem to change anything nor did zooming in or out.

**To Reproduce**
Obtain 100K coins

**Expected behavior**
The Coin logo to stay the left of your coin count.

**Screenshots**
![Normal Coin logo Placement](https://user-images.githubusercontent.com/88407825/130846925-296edd7c-4c02-463c-8978-2b4b6b71ad17.png)
![6figure coin logo placement](https://user-images.githubusercontent.com/88407825/130847011-dc2639a1-777a-42ac-96a1-3e4be1997aa3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS High Sierra,
 - Browser [e.g. chrome, safari] Chrome, Brave. Safari keeps the coin logo on the left
 - Version [e.g. 22] V1

**Additional context**
I'm not sure if this was intentional or not. Just an inconsistency.

**Comment by CameronCT** [comment]
Likely cache related as I am unable to recreate this on several devices.
