### ISSUE TITLE
Queue time resets to zero after every hour

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#102]
**Describe the bug**
Have been queueing for three hours now, looks like every hour the timer resets to zero and starts again.

**To Reproduce**
Queue for an hour without finding a match in 1 vs 1 duels.

**Expected behavior**
The timer includes hours

**Screenshots**
![image](https://user-images.githubusercontent.com/1338129/131506270-2a1ee3cf-ef2f-4453-8328-1bc82b8a7e2e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Stable

**Comment by popey456963** [comment]
After an unknown amount of time it also just caps for some reason and stays at `00:00`.  I _believe_ it's still searching?

![image](https://user-images.githubusercontent.com/1338129/131507723-0adeddcf-f13f-4dbb-b06d-66d11250ad99.png)

**Comment by CameronCT** [comment]
It's because the time is only formatted for 4 digits, I never added another series of digits. 

I like to think when the timer rolls over, it's a way of keeping your sanity because then you can think you just started queuing again.
