### ISSUE TITLE
Recent highscores will always grab the latest score and not the highest 

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#107]
When a score is submitted on the Recent highscores list and the player submits **another** score after that, the current score on the Recent highscores gets replaced with the newest score even if its WPM are lower than on the old score.

So for example after submitting a 150WPM and then a 130WPM the 150WPM would be replaced by the 130WPM.

**Comment by CameronCT** [comment]
Not too sure if this bug is actually a bug since the time the issue was created was still when the server was essentially catching up with scores. I'll keep open in case we get more reports.

**Comment by nathannguyen650** [comment]
Just here to report that I noticed the same thing

**Comment by Idontknowwhattocallmyself** [comment]
I also notice the same bug

**Comment by CameronCT** [comment]
Fixed has been pushed for staging.
