### ISSUE TITLE
Ranked icons not showing correctly on profile

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#108]
![image](https://user-images.githubusercontent.com/85042709/132266564-8dec563a-da4a-4435-8886-8377d3a026d3.png)
![image](https://user-images.githubusercontent.com/85042709/132266568-bc0283bb-1d00-4847-8637-7f074705c7c0.png)

https://keyma.sh/profile/Codefined-8516
https://keyma.sh/profile/DefinitelyNotJah-0750

**Comment by CameronCT** [comment]
Fixed next update.
