### ISSUE TITLE
[Keep open] End Game button not working randomly

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#109]
Random, but very rarely the End Game button for the lobby leader breaks at the end of a match and freezes the lobby, thus forcing the lobby leader to refresh the lobby.

As of right now we have no idea how to reproduce this bug and thus don't know how to fix it. So if anyone has an idea what might be the cause of this please post it below.

Edit: It seems that the End Match (Or Abort Match) button can also be affected by that

**Comment by aevi72** [comment]
Update: It seems that the button breaks when the lobby leader is reassigned and starts a game. The button on the first game always breaks for the new lobby leader but works fine in the second game. (Thanks @M94SS for the help!)

It looks like the first game with a new lobby leader just outputs 
```
42/lobby,["forceEndMatch", {}]
0: "forceEndMatch"
1: {}
```
and leaves out `forceEndLobby`
while all the other normal games output
```
42/lobby,["forceEndMatch", {}]
0: "forceEndMatch"
1: {}

42/lobby,["forceEndLobby", {}]
0: "forceEndLobby"
1: {}
```

**Comment by CameronCT** [comment]
Pushed update into staging - please confirm if fixed.

**Comment by aevi72** [comment]
Works fine on staging.
