### ISSUE TITLE
Settings menu overlapped by the end game screen (Not game breaking)

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#111]
Describe the bug:

When the game ends and you click on the settings button " ⚙️ " it's inaccessible except for the exit button so you would have to exit the game and go to the main page of the website 

To Reproduce:

1. Start a game
2.(After the game ends) click on the settings button "⚙️" on the top right
3. See error

Expected behavior:

The setting menu should be on top of the end game screen. Also you shouldn't have to navigate over the front page to be able to access the setting menu

Screenshots:

https://imgur.com/p5epsEk

 - OS: Linux Lite
 - Browser: Chrome

**Comment by CameronCT** [comment]
I would recommend clearing cache as I cannot re-produce this.
