### ISSUE TITLE
Daily ladder not starting automatically.

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#112]
Once the current daily ladder is finished a new one isn't created automatically.
This applies to all variants of the daily ladder.

![image](https://user-images.githubusercontent.com/85042709/132269320-63eefcdc-acdb-4163-b0d6-6ea76fbe2c38.png)
![image](https://user-images.githubusercontent.com/85042709/132269325-741e6c6d-2767-456a-8421-feaaffba8246.png)

**Comment by CameronCT** [comment]
Fixed
