### ISSUE TITLE
"Fill form" drop down in the input box randomly popping up

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#113]
**Describe the bug**
When I type into the input box during dictionary, it momentarily flashes an input box.  Not gamebreaking, but it's a huge visual distraction.  I have captured a video of it and attached it.

**To Reproduce**
Play dictionary a few times
Notice that the "Fill form" drop-down appears below the input box on Chrome

**Expected behavior**
Input box should not be flashing a "fill form" drop-down

**Screenshots**
See video

**Desktop (please complete the following information):**
Windows 10
Latest version of Chrome
Not sure if this matters, but I was using incognito because I couldn't see the sign-in option without being incognito.

**Additional context**
I was using Incognito Chrome.  This has happened before in the staging.keyma.sh site without being incognito though.

https://user-images.githubusercontent.com/87476305/132318908-d2abf143-0f7e-4154-a2cd-f614048fe9bb.mp4

**Comment by nathannguyen650** [comment]
I did 10 more dicts and did not encounter this bug.  It seems to be random, but it does happen.

**Comment by nathannguyen650** [comment]
on the 12th dict, the bug occurred, except this time it was way worse.  popped up every other word.  just to clarify, this is the same autofill box that shows up when you're signing up for a new account on a website

**Comment by CameronCT** [comment]
Despite functionality for `autoComplete="off"` is what you're supposed to do. Setting it to `"nope"` or `"new-password"` is a potential fix for this bug.

Pushing update live.
