### ISSUE TITLE
The ranking of the players are resetting [NOT URGENT JUST A VISUAL BUG]

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#114]
**Describe the bug**
The ranking of the players is resetting in every page in the dictionary section 

**To Reproduce**
1. Play a dictionary game 
2. Play the game normally 
3. Scroll down to the ranking of the most recent scores 

**Expected behavior**
The number should be continued from 30 (the last rank in the first page) to 31 (as the first rank in the second page). and then from 60 (as the last rank in the 2nd page) to 61 (as the first rank in the 3rd page) and so on...

**Screenshots**
https://user-images.githubusercontent.com/85746211/132319680-ea62fee0-dabc-4ad4-a911-d7c7b561f463.png
(a screenshot from the second page)

**Desktop**
 - OS: WIndows and Linux (a shared problem)
 - Browser: Chrome

**Additional context**
This is actually done "right" in the "Daily Ladder".

**Comment by CameronCT** [comment]
Will be fixed next patch.
