### ISSUE TITLE
Quitting in casual should count as a loss to the player

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#115]
**Is your feature request related to a problem? Please describe.**
Otherwise people dodge too much so their K/D ratio stays high

**Describe the solution you'd like**
Quitting still counts as finishing a casual game

**Describe alternatives you've considered**
None

**Additional context**

**Comment by CameronCT** [comment]
If I really care in the future I can just add Quits to the Losses. The quits are still tracked, just not publicized.
