### ISSUE TITLE
Casual wins should only count if there is another person in your lobby

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#116]
**Is your feature request related to a problem? Please describe.**
Otherwise people gain most of their wins against themselves

**Describe the solution you'd like**
A win only counts if there is at least one other person in your lobby.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by CameronCT** [comment]
Unfortunately introducing this would create confusion for other players who are already used to the system.
