### ISSUE TITLE
Daily ladders duplicating themselves

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#117]
After fixing the daily ladders not being created automatically https://github.com/Keyma-sh/game-tracker/issues/112, the daily ladders now appear automatically, though every ladder in every language is duplicated (except the consistency ladder, that one works fine).

![image](https://user-images.githubusercontent.com/85042709/132355976-37f5ee27-7c60-4c0b-a394-ac85764de48b.png)

**Comment by CameronCT** [comment]
Not a bug, I manually created them on accident.
