### ISSUE TITLE
Custom Texts "breaking" the lobby

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#118]
A short custom text will always break the lobby if it's small enough to get the "You have made too many mistakes!" scenario. If that happens to one player the lobby freezes for everyone.

**Comment by CameronCT** [comment]
Made it so Custom matches removes the "too many mistakes". Custom matches are technically a sandbox use, might as well treat it as such.

**Comment by CameronCT** [comment]
Fix pushed to staging.
