### ISSUE TITLE
Clicking keys on the keyboard bugs the next game [the next game doesn't start]

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#119]
**Describe the bug**
After playing a normal game and clicking the "Next Game" button any other key-presses on the keyboard including "alt" (for alt+tab) doesn't get you to the next game instead you would be taken to the main front page and a message shows on the top right of the screen as shown in the screenshot under. And then it keeps loading seemingly forever looking for a game (waited for 5 mins and it was still loading) also as shown in the screenshot under. 

**How To Reproduce**
1. Start a normal game
2. Play the game normally
3. Scroll down to the "Next Game" button
4. Click the "Next Game" button
5. press some keys before the next game starts
6. See Bug

**Expected behavior**
Pressing any key on the keyboard shouldn't prevent the next game from starting

**Screenshots**
(The Error Message)
https://user-images.githubusercontent.com/85746211/132445187-c18a4b4f-51ab-4f03-b706-6692d53bfc16.png

(Finding Game Loading)
https://user-images.githubusercontent.com/85746211/132445212-a688cb61-5a1b-4470-b511-53deb457d655.png

**Desktop (please complete the following information):**
 - OS: Linux Lite
 - Browser: Chrome

**Additional context**
Even refreshing the page sometime doesn't work and the bug keeps repeating. I only had to refresh twice or three times before the bug goes away, but I think it can go for more time than that.

**Comment by CameronCT** [comment]
The "Too many requests" is triggered when you press the search button too many times in a row.

**Comment by Idontknowwhattocallmyself** [comment]
I only press it once, but the keyboard keys are the trigger 
I'm pretty sure of that

**Comment by CameronCT** [comment]
Are you consistently holding the button?

**Comment by Idontknowwhattocallmyself** [comment]
No 
just one normal key press

**Comment by Idontknowwhattocallmyself** [comment]
Also I just wanted to tell you that this bug is still happening 
https://user-images.githubusercontent.com/85746211/132449204-23c3689c-9eb7-43a7-b6f7-811987692e7b.png

**Comment by CameronCT** [comment]
> Also I just wanted to tell you that this bug is still happening
> https://user-images.githubusercontent.com/85746211/132449204-23c3689c-9eb7-43a7-b6f7-811987692e7b.png
> (not being able to access the settings after the game)

Unfortunately I cannot reproduce this whatsoever. Can you try on a different browser to see if it's the same issue. Do you have Dark Screen reader on?

**Comment by Idontknowwhattocallmyself** [comment]
I'll try and tell you

**Comment by Idontknowwhattocallmyself** [comment]
> > Also I just wanted to tell you that this bug is still happening
> > https://user-images.githubusercontent.com/85746211/132449204-23c3689c-9eb7-43a7-b6f7-811987692e7b.png
> > (not being able to access the settings after the game)
> 
> Unfortunately I cannot r

as you can see it's not a browser problem 
https://user-images.githubusercontent.com/85746211/132599622-327178a6-c08d-4e1b-8340-3cf8b70285c5.png

**Comment by CameronCT** [comment]
What is your system specs, you have Linux Lite. But what is your actual computer's make and model with a list of what it has.

**Comment by Idontknowwhattocallmyself** [comment]
Standing screen display size:     ‎11.6 Inches
Max Screen Resolution:     ‎1366x768 pixels
Processor:     ‎1.6 GHz celeron
RAM:     ‎2 GB SDRAM
Memory Speed:     ‎1.6 GHz
Hard Drive:     ‎32 GB eMMC
Graphics Coprocessor:     ‎Intel Integrated Graphics
Chipset Brand:     ‎Intel
Card Description:     ‎Integrated
Wireless Type:     ‎802.11bgn
Number of USB 2.0 Ports:     ‎1
Number of USB 3.0 Ports:     ‎1 
Average Battery Life (in hours):     ‎10.45 Hours
(just tested that the notification button has the same issue too)

**Comment by CameronCT** [comment]
Yeah your problem is that your Laptop is not made for much use - and I bet "Linux Lite" has some drivers removed that doesn't allow Chrome to utilize some more modern tools (such as `z-index` or other values)

**Comment by CameronCT** [comment]
Also, extended rate limiter and pushed to staging. Also removed the error
