### ISSUE TITLE
Error on last word of text

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#12]
Problem: Typing an error on the last word of a text (too many keys) does not result in highlighting movement as it does for any other word making it hard to recover from an error on the last word.

Solution: Error highlighting should extend past the end of the text.

Pictures:
![Screen Shot 2021-05-07 at 4 34 36 PM](https://user-images.githubusercontent.com/65517819/117505555-38cbee00-af52-11eb-8fa5-94aa66441393.png)
![Screen Shot 2021-05-07 at 4 35 06 PM](https://user-images.githubusercontent.com/65517819/117505556-39648480-af52-11eb-8a28-a633ca9f12f1.png)

**Comment by CameronCT** [comment]
While this is technically a bug, this is nowhere near impactful enough to warrant a fix. However, this will be kept in mind when/if we ever recreate the text validation (since it is due for a rewrite soonish).
