### ISSUE TITLE
Clicking on "New Game" gives you an error

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#122]
Finishing a game and then clicking on "New Game" on the Match end screen gives you a "Too many requests" error. It searches for a new game and thus works fine, but the error message is distracting. Clearing cache and cookies doesn't resolve this issue.

**Comment by Idontknowwhattocallmyself** [comment]
This happens to me when I click on some keys on the keyboard, it's not just random. Also for me it bugs and the next game doesn't start.

**Comment by CameronCT** [comment]
https://github.com/Keyma-sh/game-tracker/issues/119
Related to this issue.
