### ISSUE TITLE
Consistency ladder: inaccurate calculations

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#123]
It seems like the calculation on the consistency ladder is inaccurate.
After testing the ladder thoroughly with the help of @ DAMAGED, we found out that there are two possibilities:

 - 1st: The system calculates 10 matches but also includes 0's that are in a 20-match range
 - 2nd: The system calculates the actual 20 matches (including 0's from the 20-match range) and takes that average for the ladder.
 
Not too sure what happens exactly since our manually calculated averages were always slightly off except for once. Might be worth investigating.

**Comment by aevi72** [comment]
> It seems like the calculation on the consistency ladder is inaccurate.
> After testing the ladder thoroughly with the help of @ DAMAGED, we found out that there are two possibilities:
> 
> * 1st: The system calculates 10 matches but also includes 0's that are in a 20-match range
> * 2nd: The system calculates the actual 20 matches (including 0's from the 20-match range) and takes that average for the ladder.
> 
> Not too sure what happens since our calculated averages were always slightly off and only correct once. Might be worth investigating.

**Comment by CameronCT** [comment]
Yes there is a confirmed bug.

I forgot to update one part of the code where it shifts the `recentWPM` object after a certain amount of rows. Since tournaments were always top 20 results, it would shift after the top 20 but then the array would re-average itself based on 20 results.

Fix pushed for staging.
