### ISSUE TITLE
Input Box Extension from 35 Chars

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#125]
**Is your feature request related to a problem? Please describe.**
Because of the (arbitrary?) 35 character limit on the length of a single word, longer hyphen phrases can't be completed.

**Describe the solution you'd like**
The input character limit should be increased to 60 or 70 to accommodate longer hyphen phrases.

**Additional context**
There is one text in the game that I encountered yesterday with a hyphen phrase 29 characters long. I will include an example of a text that has a hyphen phrase more than 35 characters long (will be submitted if the input character length is extended) [here](https://flcoe-my.sharepoint.com/:i:/g/personal/aldempido_student_forestlake_org/EURS9jN6_5FDoWkYg9jncU4BdKCle1mE8HcE0XkgYxIhSg?e=hnaSIx)

**Comment by nathannguyen650** [comment]
The limit would definitely need to be removed if German keyma.sh progresses.  There are plenty of German words over 35chars

**Comment by CameronCT** [comment]
According to some Google searching, the longest German word is roughly 80 characters. However I am not extending the max input length to that as the reason for the input box limit is to act as a client-side anticheat measure.

The longest German words I've seen on average are roughly around 30-40 characters therefore I'll up the limit to 50 characters.

Change pushed to staging, along with the fix of overflown text on playercards.
