### ISSUE TITLE
Bring back the "Leave lobby" button after a race in the lobby.  

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#126]
**Is your feature request related to a problem? Please describe.**
The Leave Lobby button at the end of a lobby race has been removed.  I understand this is intentional, but there are consequences to this.  If you're in a lobby with 10 speedy typists and there's one guy typing at 30 wpm, everyone will have to wait a minute or two doing nothing while the 30 wpm dude finishes his text.  Previously, we were able to leave back to the chatroom using the "Leave Lobby" button and just wait for the next match to start.  This will encourage people to kick slow typists if the button is not returned.  

**Describe the solution you'd like**
Bring back the button, but change the name to "Go Back to Chat."  

**Describe alternatives you've considered**
I'm not a Plan B kinda guy

**Comment by CameronCT** [comment]
This was originally removed from another suggestion. This issue is awkwardly trivial so I'm keeping the current functionality.
