### ISSUE TITLE
Track separation 

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#128]
**Describe the bug**
I'm getting matched up with guys who are typing 30 wpm.  There seems to be no track separation.  This might be intentional, but I just wanted to verify.  

**To Reproduce**
Race on the track.
Be fast.  
Notice you get matched up with newbies.  

**Expected behavior**
Newbies should race with newbies.  

**Desktop (please complete the following information):**
Windows 10, Chrome, latest version.  

**Additional context**
I understand due to the low playerbase, the track separation might have temporarily been removed.  I'm not sure if it's temporary or if it's even intentional.  Just wanted to create a report to confirm.

**Comment by CameronCT** [comment]
Track separation exists, however it is pretty thin right now.
