### ISSUE TITLE
Hyphenated phrases become two lines on playercard

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#129]
**Describe the bug**
Hyphenated words, hyphenated phrases, or words that are too long will create a new line on the playercard. This causes the match container to move and is disorienting in general. This is somewhat tied to #125 as both problems are a result of hyphenated phrases.

**To Reproduce**
Join a custom match and type a word/hyphenated word or phrase that is very long. (I think it overflows at around 20 characters.) From memory, I have encountered 4-5 texts that cause the new line to form.

**Expected behavior**
Any words that are too long to fit in the playercard will have ellipses on the end.

**Screenshots**
[Screenshot](https://flcoe-my.sharepoint.com/:i:/g/personal/aldempido_student_forestlake_org/EURS9jN6_5FDoWkYg9jncU4BdKCle1mE8HcE0XkgYxIhSg?e=hhJ4zL)

**Desktop (please complete the following information):**
 Issue persists on all browsers.

**Comment by CameronCT** [comment]
Already have a fix pushed into staging.
