### ISSUE TITLE
Any Introduction to Numbers lesson can't be completed without typo

### ISSUE THREAD

**Issue by ExLog** [Keyma-sh/game-tracker#13]
**Describe the bug**
Lesson didn't end after I typed all numbers correctly. I can only complete it when I made a typo at the start

**To Reproduce**
1. Go to Learn
2. Click on Introduction to numbers
3. Click on a lesson
4. Type normally, but when I typed all numbers correctly lesson didn't end

**Expected behavior**
Lesson can be completed without typo

**Screenshots**
1. Lesson didn't end after I typed all numbers correctly
![Lesson didn't end](https://user-images.githubusercontent.com/55097092/118403490-2152da80-b6a1-11eb-862f-30cf8291ad83.png)

2. The summarize Shows null when repeating the completed lesson without typo
![Summarize null](https://user-images.githubusercontent.com/55097092/118403593-accc6b80-b6a1-11eb-98f1-6260d82f84dc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Arch Linux
 - Browser: Firefox
 - Version: 88.0.1

**Additional context**
These are details that I catch when this bug happened:
1. While typing, WPM and accuracy doesn't change at all
2. When I managed to complete it with typo, it always shows 0 mistakes and 100% accuracy
3. The summarize shows null when repeating the completed lesson without typo

**Comment by CameronCT** [comment]
I am able to reproduce this, though I'm not too sure where it went broken as I've completed this whole course before. I will take a look into this over the coming days, a push will likely be fixed when we launch the redesign (~1-2 weeks).
