### ISSUE TITLE
Unable to get into a race, starting a race too late, unable to finish a race.  

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#130]
**Describe the bug**
This is a problem that has been plaguing me during my entire time with keyma.  I believe due to my proximity to the servers, I am unable to consistently join races.  When I am fortunate enough to join races, the timer often freezes and I end up starting the race 2-5 seconds late.  On some occasions I'm able to complete the text, but it doesn't register me as finishing it.  So I'm just stuck there watching the timer tick down.  After the timer ticks all the way down, I'm still stuck so the only option is to quit the race.  

My ping is usually around 500 on an average day.  On a good day, it's 300.  Today, my ping was around 1000-2000.  

This post was created solely to show you the SEA experience on keyma.  I'm sure you're already aware of the problem, but you probably don't have video or know the minutiae.  

**To Reproduce**
- Be located far from the servers.
- Play keyma.
- Some days you won't be able to get into races at all.  Some days you may get lucky.  Some days you may get into races, but you will start late or you won't be able to finish a race.  
- idk don't expect me to be as detailed as Aevi.  

**Expected behavior**
I just want to join a race consistently.  I often start races late or I am unable to finish races.  There's also a theory that refreshing while getting stuck on the loading screen will add to your quits.  

**Screenshots**
https://user-images.githubusercontent.com/87476305/132832075-06baf486-9b0a-4ff3-906f-e7c3eb6273ec.mp4

**Desktop (please complete the following information):**
Windows 10, Firefox, latest version.  

**Additional context**
Using a VPN doesn't help (and I didn't expect it to for obvious reasons).  If you want to capture the Indian/SEA market, a greater focus on server location is essential.  

I tested my internet immediately after the video.  98 down and 100 up.  Internet is working just fine.

**Comment by CameronCT** [comment]
Closing since this issue is a dead end of #1. The reason why he made this issue is because it has been happening more recently, but unfortunately there's not much we can do as we are still waiting on Cloudflare to communicate with us / find a resource that has a proper solution.
