### ISSUE TITLE
Keyma.sh profile avatar doesn't sync the authenticated Discord avatar (Discord OAuth)

### ISSUE THREAD

**Issue by ExLog** [Keyma-sh/game-tracker#131]
**Describe the bug**
Keyma.sh avatar doesn't change after relog  (Discord OAuth).

**To Reproduce**
1. Sign out my existing Keyma.sh account
2. Sign in again using Discord OAuth
3. The Keyma.sh avatar doesn't sync my Discord avatar

**Expected behavior**
Avatar should change and sync with my Discord avatar

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 92.0

**Comment by Syndric** [comment]
I changed mine a few days ago. It changed after a few hours and I was pretty happy with it. Maybe give it a little time?

**Comment by CameronCT** [comment]
Pushed update into staging.
