### ISSUE TITLE
The graph and the end game card are giving different results 

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#132]
**Describe the bug**
The final average wpm on the end game card and on the graph are not matching up 

**To Reproduce**
I don't think there is a trigger 

**Expected behavior**
The result on the graph and on the final end game card should be the same

**Screenshots**
https://user-images.githubusercontent.com/85746211/132973657-5a02ea3b-ad30-47ee-b596-5a65c30c354b.png
https://user-images.githubusercontent.com/85746211/132973662-81407c7f-c040-409b-a0d8-cbdabe664114.png

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**
calculated it myself and it should be the one on the graph [the calculation I did: (41-4)/(29/60)=78]

**Comment by CameronCT** [comment]
The graph shows your WPM for every second word. On this particular match, your last word in the text was on an odd number and not an even number hence the discrepency.

**Comment by Idontknowwhattocallmyself** [comment]
Then maybe as and enhancement you should make it the same or the average between the 2, so people wouldn't keep talking about how it's different.

**Comment by CameronCT** [comment]
If I made it the average between the two, then it would cause more confusion - and if I make it the same, then the same issue would occur.
