### ISSUE TITLE
Improvement mode 

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#133]
**Is your feature request related to a problem? Please describe.**
Nopes.  An optional "Improvement mode" feature that collects your mistakes at the end of each race.  It makes you type your mistakes 3-5x each (custom number) before being able to continue to the next race.  

**Describe alternatives you've considered**
At the very least, enable a text box at the end of the race so the user can choose to type the mistakes.  

**Additional context**
People are not focused on improving the words they find hard to type.  With an Improvement Mode, they are forced to face the words they find difficult.

**Comment by CameronCT** [comment]
https://github.com/Keyma-sh/game-tracker/issues/35

Related to this, could potentially re-consider - but this will be a "far down the pipeline" kind of feature.
