### ISSUE TITLE
Accuracy/Speed registering incorrectly.  

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#134]
**Describe the bug**
I just blasted a dictionary text at approximately 183 WPM and with 100% accuracy.  However, it registered as 163 WPM and 97%.  

![image](https://user-images.githubusercontent.com/87476305/133450803-f57f2773-27a1-4c67-bc93-7afea8bd6011.png)

Notice how there are no mistakes listed, yet it registered as 97% accuracy.  

![image](https://user-images.githubusercontent.com/87476305/133451249-a4dbf135-ae32-48fb-9103-1a599da8817a.png)

Here's the graph.  You can see three points where I dipped down to 99.15 WPM.  Each of those three points were typed at exactly 99.15 WPM (which is something only a robot could do).    

"mix should true say crease yes seven rock move try which value face practice noise parent take world may water lost hope laugh should populate effect few vowel question experience pair die dark good center eat divide melody record come show meant rub usual put mind city molecule flow lead" 

This is the dict text in question.  It is 289 characters.  Each word is five characters.  19 seconds elapsed.  I'm terrible at math, but it should be approximately 183 WPM

![180 dictionary](https://user-images.githubusercontent.com/87476305/133451778-eefdd340-aa54-4685-bee4-4f1a063ceced.PNG)

This is a dict text with 277 characters with 18.5 seconds.  It registered at 180.  This is a screenshot from v1.  

**To Reproduce**
I have literally no idea how to reproduce it.  I suspect it's due to my lag.  Silvermium had the exact same problem and Aevi looked into it.  You can ask him about it.  Apparently it was something about some extreme lag between the inputs.  

**Desktop (please complete the following information):**
Windows 10, Firefox

**Additional context**
Was racing as a guest account.  Don't have any records of it.  This has happened to me at least once before, but probably more.

**Comment by CameronCT** [comment]
Yeah this issue will be insanely hard to debug. It's truly possible that you had a missed packet which caused the error (maybe it was a mistake on the space).

**Comment by nathannguyen650** [comment]
> 
> 
> Yeah this issue will be insanely hard to debug. It's truly possible that you had a missed packet which caused the error (maybe it was a mistake on the space).

No worries, I understand.  But to get 97% accuracy, I would have to make a mistake on the space bar quite a few times.  I remember very clearly it was a perfect race because I did me a little fist pump :(

**Comment by CameronCT** [comment]
Well I feel better knowing you experienced this in v1 too, so I know it's not something new in that sense.

**Comment by nathannguyen650** [comment]
> 
> 
> Well I feel better knowing you experienced this in v1 too, so I know it's not something new in that sense.

No, no.  Sorry to burst your bubble but it didn't happen in v1 :(

**Comment by CameronCT** [comment]
I mis-read, I thought you said you did ;(

**Comment by nathannguyen650** [comment]
![image](https://user-images.githubusercontent.com/87476305/133751546-fc979422-e68e-48a7-8543-c75693f72eb8.png)

This race was approximately 173'ish, but registered at 154.  

![image](https://user-images.githubusercontent.com/87476305/133753090-03ccd530-79f1-43a9-8174-dce6d585e27d.png)

That huge cliff is where the lag spike occurred.  Notice that I got 100% and I did not stutter nor pause on any word.  

I have to emphasize it's a pretty serious issue affecting about 1/5 races on average (1/3 at worst).  When it does affect the race, it's by about 10 WPM usually.  At worst, it affects the race by 20 WPM.  I was actually glancing at my ping while racing and saw exactly when it had a spike.  

Strangely enough, I think the timer is actually accurate.  Perhaps there's a different way to calculate WPM using the elapsed timer and characters?

**Comment by nathannguyen650** [comment]
btw, smol flex.  I guessed that it was 173 by literally just instinct.  

I just did the math using a formula I found literally two minutes ago.  The confirmed speed is a little over 171.  I'm telling you, I'm good at feeling my speed.

**Comment by nathannguyen650** [comment]
WPM seems to be accurate in lobbies.  Will test further

**Comment by CameronCT** [comment]
Well with your mistake that's likely why your WPM dropped - this is still all latency based as of right now. **To clarify I am not saying you did or didn't make a mistake**

All the accuracy does is `(correct characters / (correct characters + incorrect characters)) / * 100` which makes sense if you had latency and it gave a typo based off packets catching up. 

There's no real approach as making the test run every second time for example would pose the risk of incorrect data, which poses the risk of incorrect keylogs, which poses the possibility of false-positives in terms of Anticheat and manually reviewed cheating bans.

**Comment by nathannguyen650** [comment]
This is also happening to Silvermium.  Here's a screenshot of his dictionary race on the average ladder:

![image](https://user-images.githubusercontent.com/87476305/133827688-eed876b7-5000-4189-9571-8c7f3b351c44.png)

The text is 270 characters with space and 21.3 seconds elapsed.  Using those numbers, the correct WPM should equate to 152.11.   His problem is actually worse than mine

**Comment by nathannguyen650** [comment]
> 
> 
> This is also happening to Silvermium. Here's a screenshot of his dictionary race on the average ladder:
> 
> ![image](https://user-images.githubusercontent.com/87476305/133827688-eed876b7-5000-4189-9571-8c7f3b351c44.png)
> 
> The text is 270 characters with space and 21.3 seconds elapsed. Using those numbers, the correct WPM should equate to 152.11. His problem is actually worse than mine.
> 
> Also, take a look at his accuracy. He only made two mistakes, yet it registered as 84%.

What do you think about having a system that double-checks the characters/elapsed time at the end of the race?

**Comment by CameronCT** [comment]
If I added a system that double-checked, then it would still run into the same issue with cheating / anticheat issues.

**Comment by CameronCT** [comment]
Due to the complexity of this issue, I have opened another Cloudflare ticket and we will see if we get a response.

**Comment by nathannguyen650** [comment]
![image](https://user-images.githubusercontent.com/87476305/133885173-6e12b81c-db6b-42e3-9be5-1f18be161093.png)

I just want to confirm that this isn't a problem exclusive to just dictionary.  It happens to quotes as well.  I still stand by my statement that it affects 1/3 races.

After calculating, the correct score should have been 180.1801 WPM.  Yes, there was a ping spike :(

**Comment by CameronCT** [comment]
Again, I submitted an actual ticket. Until then there's not much I can do.

**Comment by CameronCT** [comment]
Also WPM will be based off first keystroke delay on top of elapsed time - the two aren't mutually extracted from eachother.

**Comment by CameronCT** [comment]
Closing this until Cloudflare responds.
