### ISSUE TITLE
"Sudden Death" Challenge does not update on completing a custom match.

### ISSUE THREAD

**Issue by Zadeos** [Keyma-sh/game-tracker#135]
**Describe the bug**
Trying to complete a custom match with mistakes allowed for the challenge requiring 1 match fitting that description, upon completing the match, the count didn't go to 1/1 and stayed as 0/1.

**To Reproduce**
1. Go to https://keyma.sh/ and click the "CREATE" button in the Custom section
2. Click on "START MATCH"
3. Complete the match
4. Go to the "CHALLENGES" page and observe the counter not being updated.

**Expected behavior**
Upon completing the custom match, I should expect going back to the challenges screen I would have a 1/1 counter allowing me to redeem my reward. However, it never goes up to 1/1 and stays at 0/1.

**Screenshots**
![image](https://user-images.githubusercontent.com/16419796/133548459-47b737d1-6428-4844-aaca-96ddcd348b4e.png)
The challenge in question 9:15 PM
![image](https://user-images.githubusercontent.com/16419796/133548540-b406e9b5-a091-43b7-a424-48e08f5dde07.png)
My completed custom match 9:16 PM
![image](https://user-images.githubusercontent.com/16419796/133548609-a1c47626-1268-4160-9ca4-0b3c9c5eda4b.png)
My challenges page after the custom match 9:17 PM
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.29.81

**Additional context**
When playing in a custom match with 🌵M94SS🌵#7305 (523953934713225223), their challenge for 100% accuracy got updated correctly while mine did not.
![image](https://user-images.githubusercontent.com/16419796/133549011-a06b1255-7afa-413b-a7ef-a8506d057131.png)

**Comment by CameronCT** [comment]
Will take a look into it - technically this challenge wasn't supposed to exist so I'll probably go through and remove all of these soon.

**Comment by popey456963** [comment]
Tried this twice.  Once with Zenjin and once without.  Both times the challenge didn't update after getting 100% accuracy.

**Comment by CameronCT** [comment]
These challenges will be removed next update.
