### ISSUE TITLE
Ability to type during countdown (CUSTOM RANKED).

### ISSUE THREAD

**Issue by DefinitelyNotJah** [Keyma-sh/game-tracker#136]
**Describe the bug**
I was able to type during countdown in a 1V1 DUEL MODE custom lobby during the second match.

**To Reproduce**
![2021-09-18_15-59](https://user-images.githubusercontent.com/63221794/133893195-743ef5f8-71c8-4a72-be3c-50b4f36b20e7.png)
Custom lobby => 1V1 Duel Mode.
Custom quote is: `yes yes yes`.
So basically, in order to replicate the bug, you have to type quite fast & keep typing/spamming until the match ends & the second ones appears.
I'm not quite sure on the details tho.

**Expected behavior**
Obviously the unability to type during countdown.

**Screenshots**
SS 1:
![2021-09-18_15-56](https://user-images.githubusercontent.com/63221794/133893086-9154ca80-e2f2-4146-a073-7af021908e8d.png)
**SS2:**
![2021-09-18_15-53_1](https://user-images.githubusercontent.com/63221794/133893087-c1051c34-fff9-4f01-9f65-c6fb3f3d3223.png)
**SS3:**
![2021-09-18_15-46](https://user-images.githubusercontent.com/63221794/133893111-b620a3f8-96ad-42d9-90db-e48d4eb2c88c.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.04
 - Browser Vivaldi
 - Version 4.1.2369.21‑1

**Additional context**
For SS2, the score was not able to submit and WPM started calculating when the countdown ended (inaccurate).
![2021-09-18_15-54](https://user-images.githubusercontent.com/63221794/133893351-1abd5f19-1fc5-4a76-9cf7-786d878d4596.png)
For SS3, I was only able to input/type the letter `Y`, could not press other keys.

**Comment by DefinitelyNotJah** [comment]
> So basically, in order to replicate the bug, you have to type quite fast & keep typing/spamming until the match ends & the second ones appears.
As far as I remember, I kept typing until the match ended and the game moved on to the next match, which allowed me to type during countdown.

**Comment by CameronCT** [comment]
Taken a look at this issue, this is pretty difficult to replicate (maybe easier on higher latency situations). However, there's not much I can do since it's a matter of state registration between the components. Meaning if the component hasn't mounted quite yet, then it can't prevent typing in between those states.
