### ISSUE TITLE
Pause game feature

### ISSUE THREAD

**Issue by abdo2048** [Keyma-sh/game-tracker#138]
**Is your feature request related to a problem? Please describe.**
Not much a problem. It's a fancy feature I guess.

**Describe the solution you'd like**
The ability to pause the game at any time like Monkeytype, whether I play alone or with someone (in this case the game will be paused for me only).
The pause would be activated by:
- Moving to another tab.
- Clicking outside the page.
- A shortcut to pause (would be good if there is no other tabs to switch to using Ctrl+Tab)

Also, when we pause, we should be able to see the text/word that we are going type next when Un-pause the game (Unlike Monkeytype where it's blurring the text/wrod when you pause, so you don't know what will you type when you Un-pause the game.)

**Describe alternatives you've considered**
N/A

**Additional context**
I gave you my opinion and maybe you see it interesting or a part of it that you could take and customize it according to your way, especially maybe pausing an online game would be somehow unfamiliar option. Thank you for your efforts.

**Comment by Miodec** [comment]
But Monkeytype doesn't have a pause feature..

**Comment by CameronCT** [comment]
The only point for us to add a pause feature is for if someone has network issues in the middle of a match (for custom / spectating purposes only) - that's really the only point. I can't enforce a pause feature on a public match in Keyma.sh, that wouldn't be fair and would be heavily abused.
