### ISSUE TITLE
Leaving custom lobbies should have a prompt

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#140]
**Is your feature request related to a problem? Please describe.**
I have a natural tendency spam the click button in custom lobbies. I'm sure other people accidentally click on the wrong things too sometimes. However, there isn't any confirmation. As a result, you leave the lobby. When you go back in, the host has to move you again and all the chat is erased. I think that it is inconvenient.
 
**Describe the solution you'd like**
I'd like to see a prompt appear that asks, "Are you sure you want to leave this lobby?" when someone clicks on something that would take them to another page in a custom lobby.

**Describe alternatives you've considered**
None

**Comment by aevi72** [comment]
Pretty pointless since it should be self-explanatory that clicking on buttons that lead to other sites or parts of Keyma.sh would make you leave a lobby automatically. A prompt would be annoying as well if you really want to leave the lobby and need an extra click to do so.

**Comment by Syndric** [comment]
Following that line of thought, is it really necessary to have the "are you sure you want to leave this game?" prompt when leaving a match?
