### ISSUE TITLE
Dividing the homepage screen results in a wonky layout

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#141]
**Describe the bug**
Attempting to use a split screen configuration results in this weird home screen layout. 

**To Reproduce**
1. Go to homepage
2. Set Chrome zoom to 100% and set the page window size to 1333x1187
3. You should see it.

**Expected behavior**
Not sure what the "correct" solution would be here - maybe turn into the 2x2 layout?

**Screenshots**
[Imgur link here](https://imgur.com/a/JPI7ewy)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - 93

**Comment by CameronCT** [comment]
I mean no resolution for 1333x1187 exists so I don't necessarily know why this is really a bug. Nonetheless I'll see about fixing it.

**Comment by Syndric** [comment]
Users who use 1440p split-screen for youtube, discord or something else generally will be in the ballpark

**Comment by CameronCT** [comment]
Fixed in next patch
