### ISSUE TITLE
"Colorful Triangles" playercard does not display on leaderboards

### ISSUE THREAD

**Issue by Aicaya** [Keyma-sh/game-tracker#143]
**Describe the bug**
When using the Colorful Triangles playercard, no image will show on any leaderboards (the highscore list on the home screen, for example).  Doesn't matter how long I wait, what browser I'm using (tested on both Firefox and Chrome/Chromium), etc., and of all the playercards I've gotten that is the only one with that issue.  Every other card displays correctly.

**To Reproduce**
1. Purchase "Colorful Triangles" card and set it as your own
2. Finish a match with a high-enough WPM to qualify
3. Check leaderboards

**Screenshots**
![keymash-bug](https://user-images.githubusercontent.com/17915907/134992912-7c5f2cc6-be42-4124-9b0e-d34100b9f489.png)

**Comment by Syndric** [comment]
Same thing on my side.

**Comment by aevi72** [comment]
Playercard is working as intended as of now.
