### ISSUE TITLE
Error 520

### ISSUE THREAD

**Issue by Dominic-Hoe** [Keyma-sh/game-tracker#144]
**Describe the bug**
I keep getting Error 520 from CloudFlare when finishing a ladder match and being redirected to the ladder, and sometimes when just going to the main page (https://keyma.sh)

**To Reproduce**
1. Participate in a ladder match
2. Finish
3. See error

**Expected behavior**
To be able to view the ladder without receiving an error, which makes the site unusable.

**Screenshots**
![image](https://user-images.githubusercontent.com/78672762/135357066-3dac592e-9015-4d4d-9a9d-16baae6d209f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0
 - Browser: Vivaldi (which is Chromium based)
 - Version: 97

**Comment by cyan-amethyst** [comment]
Your issue should be resolved after deleting the Keyma.sh cookies and cache (steps are shown in the photo added below).

![error520](https://user-images.githubusercontent.com/87863597/135357616-459b78db-f5a5-447d-8b87-1a216a100378.png)

**Comment by Dominic-Hoe** [comment]
Worked, thanks
