### ISSUE TITLE
Increase character limit for customs quote in custom matches

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#145]
**Is your feature request related to a problem? Please describe.**
The max length of custom quotes for custom matches is just a tad bit too short. 700 characters is pretty small. What if someone wants to type a really long quote and focus on stamina?

**Describe the solution you'd like**
I'd like to see the max characters for a custom quote in custom matches increase to 1000 or 1200.

**Comment by CameronCT** [comment]
This was increased a while ago, I just never mentioned it.

**Comment by Syndric** [comment]
The custom text box still stops at 700 characters

**Comment by CameronCT** [comment]
I'll check in a bit. Maybe I set it to 1000 for the actual validation but not the front end.
