### ISSUE TITLE
WPM stop counting when try to close the website tab

### ISSUE THREAD

**Issue by quitsv** [Keyma-sh/game-tracker#146]
**Describe the bug**
(Sorry for my bad English) When I press cancel on the confirmation on closing the keyma.sh tab on my browser, the wpm and text counter stopped working and I could no longer be able to continue the race.

**To Reproduce**
1. Start a match
2. Try closing the browser tab for keyma.sh website so the confirmation request pops out
3. Cancel the confirmation
4. Problem appears

**Expected behavior**
The counter for WPM and words start to count again and I would be able to finish.

**Screenshots**
![image](https://user-images.githubusercontent.com/37143597/135715423-0146937e-9f00-4bfc-bca6-2d54284328af.png)
*notice that the counter for the word and the counter will stay the same after the bug. But, the timer will still be going.

**Desktop**
 - OS					: windows 10 Home
 - Browser				: Opera GX and Chrome
 - Version (For Opera)	: Version LVL 3 (core: 79.0.4143.73)
 - Version (For Chrome) : 94.0.4606.61 (Official Build) (64-bit)

**Comment by CameronCT** [comment]
People heavily requested we added this. While the cancel option should dis-engage, it's a mixture of browser functionality that I can't overwrite and even if I did. It's very hard for me to force a user to reconnect to its exact state, this is why issues like #1 will likely not be resolved by me.

It's simply hard to create a disconnect management that can be even remotely reliable.
