### ISSUE TITLE
Clicking 'Retry' after failing QWERTY_BASIC/1 redirects to QWERTY_BASICS/undefined

### ISSUE THREAD

**Issue by johnny-prencipe** [Keyma-sh/game-tracker#15]
**Describe the bug**
The button to retry a failed QWERTY course (only tested on QWERTY_BASICS/1) redirects to QWERTY_BASICS/undefined

**To Reproduce**
1. Go to learn/QWERTY_BASIC/1
2. Fail the test
3. Click retry

**Expected behavior**
It should redirect to learn/QWERTY_BASIC/[lessonNumber]

**Screenshots**
![image](https://user-images.githubusercontent.com/66484382/118734533-76066a80-b7f3-11eb-95b2-70c57d12d11f.png)

**Desktop (please complete the following information):**
   - Big Sur
   - Chrome
   - Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**
Not tested on other lessons but i assume the same issue

**Comment by CameronCT** [comment]
Confirmed bug, added it into next week's update.
