### ISSUE TITLE
Not able to get 100% accuracy even if having no mistakes

### ISSUE THREAD

**Issue by Killer8Hyper** [Keyma-sh/game-tracker#157]
**Describe the bug**
Seems like I cannot get 100% accuracy, please fix this kind of error. I am experiencing this five times now... and I cannot finish the challenge. Also, there is a bug when you type one letter wrong and still get 100% accuracy in public matches.

**Screenshots**
![image](https://user-images.githubusercontent.com/69343139/142184386-a4b70332-292c-4ee2-b04c-92e022d8265e.png)

**Desktop (please complete the following information):**
 - Chrome Version 96.0.4664.45

**Comment by Killer8Hyper** [comment]
The bug where you type one letter wrong is only applicable in dictionary.

**Comment by CameronCT** [comment]
Will look into it, thanks.

**Comment by CameronCT** [comment]
If possible can you record a match where this happens as well, will help with the reproducing.

**Comment by Veirt** [comment]
I've experienced those bugs as well. Here's the recorded video

100% Accuracy 1 mistake
> https://user-images.githubusercontent.com/55097092/142347163-7e5948c2-4ed6-404c-93ab-380fb9bb1d73.mp4

98% Accuracy 0 mistake
> https://user-images.githubusercontent.com/55097092/142347707-e7d38170-77a4-42cf-9b13-2d1c09577e54.mp4

**Comment by CameronCT** [comment]
Will be fixed in next update, re-open if issue persists
