### ISSUE TITLE
'Numbers' lesson hangs when completed w/ top-row numbers

### ISSUE THREAD

**Issue by johnny-prencipe** [Keyma-sh/game-tracker#16]
**Describe the bug**
Numbers lesson hangs without completing when using horizontal number row

**To Reproduce**
1. Go to /learn/NUMBER_BASIC/0
2. Complete lesson using top numbers bar
3. Application will hang

**Expected behavior**
It should complete as normal

**Screenshots**
![May-18-2021 16-30-11](https://user-images.githubusercontent.com/66484382/118736195-d0ed9100-b7f6-11eb-81d8-744968035073.gif)

**Desktop (please complete the following information):**
  - Big Sur
  - Chrome
  - Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**
using TKL, not tested with numpad

**Comment by CameronCT** [comment]
Related to this issue https://github.com/Keyma-sh/game-tracker/issues/13
