### ISSUE TITLE
A trick to finish the hardest challenge ever in Keyma.sh

### ISSUE THREAD

**Issue by Killer8Hyper** [Keyma-sh/game-tracker#163]
This issue will be a great help if you haven't known this error. But if the team is on the way to fixing it, please close this issue and thanks.

**
I don't think it's a bug in the game but a code that needs improvements in logic.

So, when I played ranked with someone, I noticed that some of them were not playing, then I figured out why they were not playing the game. It is due to the challenge for us to finish within 24 hours, that is 'Complete 20 Custom/Ranked Matches (100% Accuracy)'. Basically, if you play ranked and don't type anything at all, you will get 100% since the code is already telling us that even if you don't play, you will still get 100% accuracy.

**To Reproduce**
1. Played ranked or play with someone in Custom match (Duel)
2. One will play and the other one don't

**Expected behavior**
 I expected that If I don't play I don't get 100% or maybe a penalty

**Recording**
- Custom match (Duel) 

https://user-images.githubusercontent.com/69343139/144040478-629690b5-98a4-4839-ac93-064c5a0d14bb.mp4

- Ranked

https://user-images.githubusercontent.com/69343139/144040520-d6732c29-75fa-42c1-9ecf-91628eda6495.mp4

**Desktop:**
 - Windows
 - Chrome
 - Version 96.0.4664.45

**Comment by CameronCT** [comment]
This challenge should likely just be removed due to abuse, if we make it so default accuracy is 0 (which will be fixed next update) then all they'd have to do is type 1 letter for it to work.

We also can't have it make sure the player finishes all rounds, as that will pretty much be a challenge to win all rounds with 100% accuracy.

We can't introduce an inactivity timer that kicks them, as they'd circumvent it by typing 1 letter every few seconds.

**Comment by CameronCT** [comment]
Going to look into finding a way to implement challenges that requires the user to win (which will probably only ever apply to Ranked)

**Comment by Killer8Hyper** [comment]
> This challenge should likely just be removed due to abuse, if we make it so default accuracy is 0 (which will be fixed next update) then all they'd have to do is type 1 letter for it to work.
> 
> We also can't have it make sure the player finishes all rounds, as that will pretty much be a challenge to win all rounds with 100% accuracy.
> 
> We can't introduce an inactivity timer that kicks them, as they'd circumvent it by typing 1 letter every few seconds.

**Comment by Killer8Hyper** [comment]
I agree that the challenge should be removed, since for me seeing that kind of challenge makes me not want to do that challenge or not play the game for the day. I am totally fine with 20 matches with 100% accuracy in public, ladder, or custom matches (not duel). However, in ranked with that challenge is a no-go even if it is 5 matches with 100% accuracy. Because there's no way I could consecutively do 3 rounds with 100% accuracy and still win, and I know for sure that I'll lose if I slow down my typing speed. Just for me... thanks :)
