### ISSUE TITLE
I can't close the popup

### ISSUE THREAD

**Issue by xzuky** [Keyma-sh/game-tracker#19]
**Describe the bug**
Whenever I go to learn a small screen pops out and I can't close it.

**To Reproduce**
1. Go to https://keyma.sh/learn
2. See the screen and the close button doesn't work.

**Expected behavior**
The popup would close.

**Screenshots**
![image](https://user-images.githubusercontent.com/58625320/119176059-ea970e80-ba6a-11eb-9897-96a6042d2bac.png)

and I see this error on the console whenever I click the close button:
![image](https://user-images.githubusercontent.com/58625320/119176171-0c909100-ba6b-11eb-9ae9-369d85454a30.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 90

**Additional context**

**Comment by CameronCT** [comment]
Related to this: https://github.com/Keyma-sh/game-tracker/issues/17
