### ISSUE TITLE
More noticeable error bar

### ISSUE THREAD

**Issue by duhby** [Keyma-sh/game-tracker#22]
Since the new update, I've changed to the large layout, and I've found it hard to notice when I've made an error when reading ahead on the next line.

A possible solution to the problem would be to add an option to make the error bar more visible by highlighting the text bar red like in the old gui.

An alternative solution would be to make the entire box red instead of just a small bar like it currently is.

**Comment by CameronCT** [comment]
Not too sure what you mean, as that part of the UI hasn't been changed since December now.

**Comment by duhby** [comment]
Sorry if I didn't make it clear, I was talking about the text bar where it shows you exactly what you are typing, before the update today it used to make the entire thing red, now it's just a small bar at the bottom that's hardly noticeable

**Comment by CameronCT** [comment]
Hm, might've been an accidental mistake that I made. There was no real intention on changing it.

**Comment by CameronCT** [comment]
Fix has been pushed.
