### ISSUE TITLE
CTRL+ALT+I and the leave button in ranked both take you back to keyma.sh/play (404 page)

### ISSUE THREAD

**Issue by OctahedronV2** [Keyma-sh/game-tracker#23]
**Describe the bug**
Title says it all, CTRL+ALT+I and the leave button in ranked still redirect you to the old play page

**To Reproduce**
1. Press CTRL+ALT+I (Personally, this keybind has never worked for me but someone else said this issue exists)

OR

1. Play a ranked match
2. Hit the leave button

**Expected behavior**
It should take you back to the home page where the play buttons are now located

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX (though I assume this affects all browsers)

**Comment by CameronCT** [comment]
While this hotkey has no use, I have resolved it to go back to the homepage again. Additionally, we have removed `CTRL+ALT+I` from our documentation despite the functionality still being there.

Fix will be pushed later today or tonight.
