### ISSUE TITLE
A "mistakes statistics" page

### ISSUE THREAD

**Issue by mochamapleaf** [Keyma-sh/game-tracker#35]
**Is your feature request related to a problem? Please describe.**
Doing matches over and over does not effectively convert to an increase in typing speed. Users can see their mistakes but cannot "learn from their mistakes".

**Describe the solution you'd like**
There could be a page containing all words that the user had made a mistake on. And present a table mapping each word to the number of times the user made a mistake on that word. In this way, the user might be able to tell which key combination or which specific key they need special work on.
Since the game is already recording every mistake the user makes in each game, this can be achieved by saving the results of each game to the account.

**Describe alternatives you've considered**
An alternative solution can be a statistics page on the typing efficiency of each key on the keyboard. The statistics could show results such as "right middle finger has a speed of 50wpm and 80% accuracy when reaching key I". In this way, the memory space required for each account is reduced. In addition, there can also be a page on different key combinations, such as "the user types 'ing' with a speed of 100wpm", or "the user often makes a mistake when typing 'tion'".

**Additional context**
It would be ideal to have a game mode specifically for users to review their mistakes and practice their weak combinations. But this could be adding more work to the development so having the statistics page would be good enough.

**Comment by CameronCT** [comment]
I really like this idea and am open to implementing some form of it, however there's a few things that we would need to evaluate in order for me to commit to adding it.

I will keep this open for now.

**Comment by CameronCT** [comment]
Closing this issue as I had planned on incorporating this with Learning but now we don't have that.
