### ISSUE TITLE
This is a bug that probably has been reported before but it hasn't been fixed. It's not urgent, it just doesn't look good

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#36]
The "mistakes" box is leaking words 
I think this only happens when you zoom in in your browser but when you make too many mistakes (can't relate) the words leak and sometimes cover the "New Game" button 
![image](https://user-images.githubusercontent.com/85746211/121689763-8c32de00-cab4-11eb-864d-482918c6a10c.png)
I don't know if this happens in all game modes, I only play regular so I know that it happens there 
(I didn't read the rest of the preview before deleting it sorry :'] )

**Comment by CameronCT** [comment]
Will be resolved in the next update.
