### ISSUE TITLE
Improve error detection behaviour on stenography world.

### ISSUE THREAD

**Issue by aerickt** [Keyma-sh/game-tracker#37]
**Is your feature request related to a problem? Please describe.**
When using stenography, extra spaces when backspacing to correct mistakes will often be detected as errors, which can be annoying. You can see some of this behaviour here: https://youtu.be/7tO2ZacxkSE. In the video I'm manually removing the spaces with an extra stroke.

What happens is that if I make a mistake and backspace, the next word I write will have an extra space before it like " keyboard". Normal if I were writing into a regular text box, undoing the last word would delete the last space as well.

There's a way to make the space output after every word, but that make it harder to write certain words that require multiple strokes (key presses). Taking the previous example of the word "keyboard", I'd first have to write "key " and because of the space output, this would result in a mistake because of the extra space in front, until I wrote the word which is "board" and at which point my steno software would backspace the space front of the first word to leave me with "keyboard ".

**Describe the solution you'd like**
It would be much better to just ignore extra spaces like on sites such as TypeRacer.

If I had to write the word "keyboard", " keyboard" (with the extra space before) should not be considered wrong (at least in the stenography world).

**Describe alternatives you've considered**
Not really anything else that could be done except keeping everything the same.

**Additional context**
https://youtu.be/7tO2ZacxkSE

Also, this is unrelated to the main issue, but the drop down menu lists the stenography world as "Stenography/Secondhand". I assume this is supposed to say "Stenography/Shorthand"?

**Comment by CameronCT** [comment]
Since this text is long and I actually discussed with you in Discord. Leaving this information here mainly for me to understand in the future.

Make it so the input for Match doesn't register the space in words that start with a space character. Make it so the space is automatically trimmed.

**Comment by CameronCT** [comment]
This will be fixed next update.
