### ISSUE TITLE
Ways to make longer quotes more attractive

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#42]
Long quotes seem to be avoided for the good ol' reason of being plain hard. Nonetheless, I think that there are multiple ways to make people play more long quotes.

1. EXP will be affected in a linear way but will have an exponential curve to the length of the text.
2. WPM will have less of an effect on EXP 
3. A new ranked stat that is the combination of the EXP from a player's top (50) XP game. (Shows on the scorecard)

Just a few suggestions and I've probably missed others.

**Comment by CameronCT** [comment]
The EXP is already calculated based on a text's length co-incide with WPM. Even if someone's WPM is lower, they are still gaining a lot more EXP compared to a short text.
