### ISSUE TITLE
Leaderboards no longer show your current place

### ISSUE THREAD

**Issue by humptyhump** [Keyma-sh/game-tracker#43]
On the Leaderboards tab that shows the "Most Wins, Highest Levels, Fastest Speed, Total Playtime" no longer show the users current place.

In the past, on the bottom, it would show you which place you're currently in. 
However, it no longer shows that and we would have to manually scroll through the pages to see what place we're in.

**Comment by CameronCT** [comment]
These leaderboards never had that option. The only leaderboards that showed your current place was Ranked, the others never showed your current place.
