### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#44]
I think that more keyboard shortcuts would be nice to have as I (and I would assume many others) hate taking my hands off the keyboard to navigate a page.
Shortcuts wanted:

Join normal quotes
Join normal dictionary
Join normal random

**Comment by CameronCT** [comment]
One idea I might look into with this, is adding the ability to customize the hot keys rather than have specific hotkeys.

**Comment by CameronCT** [comment]
This has been added in v2 as a customizable option.
![image](https://user-images.githubusercontent.com/11495748/131262278-9fb8655a-1248-469c-9d78-ade15624664a.png)
