### ISSUE TITLE
Disabling interface

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#45]
A problem that I run into when playing keyma.sh is nerves in normal lobbies. The problem with hiding WPM is that it doesn't really do much: you can still see a competitor's progress. In addition, I feel like some of the menu bars aren't really necessary when someone is typing.

What I suggest is an interface disable mode that can be turned off by a keyboard shortcut. It would look something like [this](https://imgur.com/PbB8ziL). I feel like this could accomplish a more minimalistic feel on the website.

**Comment by CameronCT** [comment]
There's a high chance I will remove this update at some point as I heavily disagree. However this change will be implemented next update.
