### ISSUE TITLE
Auto correct on mobile devices breaks submitting

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#46]
It seems like when using a mobile device with autocorrect enabled the input gets a little confused sometimes.
When having a word autocorrected and it being the same length as the word you should type out, it just registers it as a correct word and the caret moves to the next word. However, if not the same length, the word is considered "correct" beginning with a matching letter also matching with the position somewhere in the word

[For example "shipwreck" got autocorrected to "Showprogramm" in German.](https://imgur.com/a/N5YkYWv)
Keymash considered it correct until the "shipw**r**" since the **_R_** in "Showp**r**ogramm" is in the 6th position, just like in "shipwreck". Typing out the rest of the word correctly will pass the check.
"Defeat" also got corrected with "defekt" (German) and Keymash just registered the word as correct, since both are 6 letters long and ending with a T.

The same goes for auto capitalization.

However submitting after finishing the text is not possible, so if that happens on some devices by accident, people won't be able to submit. Tested it on iOS and Android and got the same results.

**Comment by CameronCT** [comment]
This technically applies to the same issue as using the arrow keys and highlighting a letter to replace it. The verification validates the last keystroke in the input and not the ones prior to it.

Next update `autoCorrect` will be set to false, as it should be. Same for `autoCapitalization`
