### ISSUE TITLE
Introduction to numbers don't work with decimal comma.

### ISSUE THREAD

**Issue by 236-52-646** [Keyma-sh/game-tracker#47]
The first lesson in introduction to numbers won't finish as it doesn't accept my input as valid.

To reproduce:
1. Use a keyboard layout with decimal comma instead of decimal point. (For example Swedish qwerty)
2. Go to the first lesson in introduction to numbers
3. Type in 3,14 with the numpad.

Expected behavior:
Either that keymash accepts both comma and point as decimal separator or that it detect which one is correct for the user.

Desktop:
Windows 10
Brave 1.22

**Comment by CameronCT** [comment]
I will add it to next update.

**Comment by CameronCT** [comment]
Actually I lied, I thought this was going to be a lot easier to implement but it is not. Will try to push a fix out soon :D

**Comment by CameronCT** [comment]
Learning center has been removed, therefore this issue is no longer relevant.
