### ISSUE TITLE
No wasting time

### ISSUE THREAD

**Issue by Xtian901** [Keyma-sh/game-tracker#48]
I'm always frustrated when I need to wait 10 seconds just to get to a game
Even if its unranked
Can you add an option where you just need to wait 3 seconds?

**Comment by CameronCT** [comment]
The 10 seconds is a base medium for players who may have significantly higher latency so they can get into a game without potentially being greeted to a countdown that is less than 3 seconds.

**Comment by Xtian901** [comment]
> The 10 seconds is a base medium for players who may have significantly higher latency so they can get into a game without potentially being greeted to a countdown that is less than 3 seconds.

Ok cool, thanks

**Comment by CameronCT** [comment]
As a later down the road QOL feature, I can potentially look into having a setting that allows you to use a desired countdown (probably a settings configuration) if you are alone in a match.

Also, if it's bothering you that much the Custom / Lobby system does have a countdown timer that can be adjusted. :)

**Comment by Xtian901** [comment]
> As a later down the road QOL feature, I can potentially look into having a setting that allows you to use a desired countdown (probably a settings configuration) if you are alone in a match.
> 
> Also, if it's bothering you that much the Custom / Lobby system does have a countdown timer that can be adjusted. :)

Yes, I used custom but I realized I don't get any wins so meh, ye, but thanks for taking my request in mind (:
