### ISSUE TITLE
(VISUAL) Some elements overlay atop the global chat window

### ISSUE THREAD

**Issue by DefinitelyNotJah** [Keyma-sh/game-tracker#49]
When opened after a lobby's match is done, some elements (players windows, etc...) will overlay the global chat window, making it nearly impossible to type.

To reproduce, simply join a lobby, have a match going with couple of people, and after you're done, try to open global chat.

**Expected behavior**
Global chat should obviously come out on top.

**Screenshots**
![2021-07-01_19-58](https://user-images.githubusercontent.com/63221794/124176462-d2bd9c00-daa6-11eb-820e-bb712ac67e1e.png)
![2021-07-01_19-50](https://user-images.githubusercontent.com/63221794/124176469-d51ff600-daa6-11eb-8717-5b919394e9e5.png)

Browser : Vivaldi 4.0

**Comment by CameronCT** [comment]
Was due to the implementation of performance mode that modifies the `zIndex`. This will be resolved next patch.
