### ISSUE TITLE
A visual bug :) [NOT URGENT]

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#50]
The textures are overlapping when you scroll down in the endgame page 

further explanation:
1. Get into a game (don't know if it's the same in ranked or not.).
2. finish the game 
3. scroll down 

Screenshot:
https://user-images.githubusercontent.com/85746211/124271772-dcc5b600-db0b-11eb-84b8-b5df906105cd.png

**Comment by CameronCT** [comment]
This will be resolved next patch.
