### ISSUE TITLE
Sidebar doesn't resize on window resizing, hides elements

### ISSUE THREAD

**Issue by johnny-prencipe** [Keyma-sh/game-tracker#51]
**Describe the bug**
Sidebar doesn't resize with different screen sizes

**To Reproduce**
1. Click on keymash logo
2. Resize window
3. See error

**Expected behavior**
The sidebar should not hide elements on window resizing

**Screenshots**
![Screen Shot 2021-07-02 at 9 04 29 PM](https://user-images.githubusercontent.com/66484382/124342473-18e33000-db79-11eb-8c4e-cd0d1cfb169b.png)
![Screen Shot 2021-07-02 at 9 04 46 PM](https://user-images.githubusercontent.com/66484382/124342476-23052e80-db79-11eb-88aa-052cadb2f662.png)

**Desktop (please complete the following information):**
 - OS: big sur 11.4
 - Browser: chrome 
 - Version: Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

**Comment by CameronCT** [comment]
This isn't a bug, the navigation is a popout side menu for static pages and other linking. It is not essential to the actual game.
