### ISSUE TITLE
Playercards/symbols are bugged out in the custom lobby chat menu

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#55]
Playercards are bugged out in the custom lobby chat menu being replaced by the default one.

![image](https://user-images.githubusercontent.com/85042709/124366519-b65d6300-dc50-11eb-812b-a5b6a43f2047.png)

**Comment by aevi72** [comment]
symbols like the Patreon Supporter symbol (and probably also the verified symbol) also don't show up in the custom lobby chat menu.

**Comment by CameronCT** [comment]
Will be resolved next patch.
