### ISSUE TITLE
People "freezing" in custom lobbies.

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#57]
Rarely people seem to somewhat "freeze" in the lobby, where they can't send messages and also can't join if a match has been started. Other people just see that the "frozen" person has just left, even though they didn't. They also don't seem to disappear from the member list. Refreshing the lobby resolves this problem.

**Comment by CameronCT** [comment]
Keeping this issue open, will be pushing a patch sometime tomorrow night. If you notice / think the problem is resolved then please close :)

**Comment by CameronCT** [comment]
Have you seen this happen since the update @aevi72?

**Comment by aevi72** [comment]
No, closing this.
