### ISSUE TITLE
Member list sometimes not updating when a player is leaving.

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#58]
The custom lobby member list is sometimes not updating itself when a player fully leaves the lobby. (not doing the weird open in another tab and still being in the lobby-thingy)

![image](https://user-images.githubusercontent.com/85042709/124368129-4fdf4180-dc5e-11eb-9518-8f3679e82f68.png)

**Comment by CameronCT** [comment]
Keeping this issue open, will be pushing a patch sometime tomorrow night. If you notice / think the problem is resolved then please close :)
