### ISSUE TITLE
Playtime leaderboard: duplicate user

### ISSUE THREAD

**Issue by LinskTypist** [Keyma-sh/game-tracker#6]
**Describe the bug**
The 76th user (Stay) appears several times in the playtime leaderboard.

**To Reproduce**
1. Go to 'LEADERS'
2. Click on 'TOTAL PLAYTIME'
3. Scroll down to '76th rank'
4. See the duplicate user (Stay)
5. That same duplicate user appears at the top of all next/previous page of the playtime leaderboard after that

**Expected behavior**
Each unique user should appear only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/83169946/115995033-e1d12b00-a5d9-11eb-8964-f18d4b05be16.png)
![image](https://user-images.githubusercontent.com/83169946/115995044-f1507400-a5d9-11eb-877d-a6d78ba31145.png)
![image](https://user-images.githubusercontent.com/83169946/115995077-180eaa80-a5da-11eb-9b86-70fa9e1aacce.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Google Chrome
 - Version: 90.0.4430.85

**Comment by CameronCT** [comment]
The issue has been fixed.
