### ISSUE TITLE
[Sudden Death] Host freezing when failing on the first letter

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#61]
**Describe the bug**
Host of the lobby is freezing when failing on the first letter, where they can't click anything and have to refresh the tab in order to fix it.

**To Reproduce**
1. Be lobby host
2. Start a sudden death match
3. Fail on the first letter

However if the host is not failing on the first letter, but on another one, they are not freezing and are perfectly fine.

**Comment by CameronCT** [comment]
Has been resolved for next update.
