### ISSUE TITLE
Ranked rank not displayed on profile

### ISSUE THREAD

**Issue by ocdy1001** [Keyma-sh/game-tracker#62]
**Describe the bug**
I played 10 or more ranked matches.
on the play page it says silver, 1095SR.
On my profile it says unranked with the empty hexagon.

**To Reproduce**
1. Play 10 or more ranked matches.
2. See your rank and SR on the play page.
3. Click on profile (icon with profile picture in top right).
4. See that rank is missing on the page.

**Expected behavior**
I would expect to see that I'm silver with 1095SR on my profile.

**Screenshots**
![keymash-bug-playpage](https://user-images.githubusercontent.com/14070776/125100119-0a48cb80-e0d9-11eb-992b-36feccbcd745.png)
![keymash-bug-profilepage](https://user-images.githubusercontent.com/14070776/125100125-0ae16200-e0d9-11eb-9418-96e94142d524.png)

**Desktop (please complete the following information):**
 - OS: Artix Linux x86_64 (5.12.14-artix1-1)
 - Browser: Firefox
 - Version: 89.0.2

**Comment by CameronCT** [comment]
What's your in game name?

**Comment by ocdy1001** [comment]
cody#9609

**Comment by CameronCT** [comment]
Fix will be pushed within the next hour or so. Was making it check for games greater than 10 instead of games greater than or equal to 10.
