### ISSUE TITLE
[Visual] Member list overlapping big ads

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#63]
The custom lobby member list is sometimes overlapping an ad. Only happens when the ad is big enough and a player joins the lobby while an ad with the correct size is being displayed

![image](https://user-images.githubusercontent.com/85042709/125132125-2d3ca500-e104-11eb-973a-2fee0bef12f5.png)

**Comment by CameronCT** [comment]
Yeah that might be a tricky one to fix as it's a responsive ad. Will look into it :)

**Comment by CameronCT** [comment]
This will be removed next update.
