### ISSUE TITLE
Lobby leader title does not transfer to next senior member of the lobby

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#66]
**Is your feature request related to a problem? Please describe.**
Whenever a lobby leader has to leave, everyone has to leave and make a new lobby.  

**Describe the solution you'd like**
Lobby leader title should be passed down based on seniority

**Describe alternatives you've considered**

**Additional context**

**Comment by CameronCT** [comment]
This has been added to v2.
