### ISSUE TITLE
The Game Freezes Randomly In The Countdown

### ISSUE THREAD

**Issue by Idontknowwhattocallmyself** [Keyma-sh/game-tracker#67]
Description of the bug:
My game seems to  freeze (only to me) in the countdown normally at 2 secs effecting the WPM of the player (making it lower)

How to reproduce the bug:
I'm pretty sure it's random but if it happens once it seems to keep happening for more games after that and then disappear somehow. 
SUMMERY:
I play normal games and it happens randomly.

Expected behavior:
When I start a game the countdown should not freeze

Screenshots:
The screen shot wouldn't prove anything (sorry I couldn't catch a video of it happening).

 - OS: Linux Lite
 - Browser: Google Chrome
 

More context:
The bug only happens to some people and the it doesn't happen to the whole lobby

**Comment by CameronCT** [comment]
Probably related to this issue:
https://github.com/Keyma-sh/game-tracker/issues/1

**Comment by CameronCT** [comment]
Closing this issue for now, but please read #1 and for future reference. There is a "bug" icon on the bottom of the gameplay screen that you can use to send logs that may help.

**Comment by Idontknowwhattocallmyself** [comment]
I was about to report this bug again because it's still happening.
I saw your comment on it and I just wanted to tell you that you're not able to click the "bug" icon when you're in the countdown, you can only access it when the test actually begins. Also the freezing now seems to not end so I wouldn't be able to report that way.
