### ISSUE TITLE
Cursor focus in learning center is wrong

### ISSUE THREAD

**Issue by willowheart** [Keyma-sh/game-tracker#68]
**Describe the bug**
When you start a lesson in the learning center, cursor is focused on the text to be typed, not the input box in which you can type (class match-input).

Very smol issue, but you have to now manually click the other box before you can start mashing your keyboard. (Unless this is expected behaviour)

**To Reproduce**
Steps to reproduce:
1. Go to learning center
2. Click on any lesson
3. Cursor is now focused on the text to be typed, not the input box

**Expected behavior**
Cursor is focused on the relevant input box so you can start typing immediately.

**Screenshots**
![image](https://user-images.githubusercontent.com/87541393/126060809-652bca04-93c8-479f-b291-c2cb9dd3ab00.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 90.0

**Additional context**

**Comment by CameronCT** [comment]
I feel like I've fixed this several times now, not too sure what keeps causing it as it's not re-producible locally.

**Comment by CameronCT** [comment]
https://github.com/Keyma-sh/game-tracker/issues/88

While this issue is not directly related, I have rewritten how the blurring events work which now works on both Chrome and Firefox.
