### ISSUE TITLE
Ban Ctrl+C and rightclick to prevent cheating

### ISSUE THREAD

**Issue by DorisCarson** [Keyma-sh/game-tracker#69]
Cheating is **too** easy. I was able to achive 360 WPM by merely **copy** the text into `xdotool`. My account was banned after 2 220+WPM and 2 300+ WPM race.

### Solution

Ban Ctrl+C, right click and make the typing text no copiable

### Screenshot
![cheating](https://user-images.githubusercontent.com/84324561/126070137-5c87c50a-8869-4a01-b36c-064192dcc3ac.png)

**Comment by CameronCT** [comment]
You cannot currently CTRL+C and CTRL+V (Copy and Paste). Your browser combined with your OS might disallow us from actually overriding that. Unfortunately websites only have a certain form of control over the browser.
