### ISSUE TITLE
Entire Game Breaks When Trying to Race on Chrome OS

### ISSUE THREAD

**Issue by atome1ectron** [Keyma-sh/game-tracker#7]
**Describe the bug**
When trying to race on a Chromebook, the entire screen disappears making it impossible to play.

**To Reproduce**
1. Obtain Chromebook and sign in using a google account
2. Open a 'Google Chrome' tab
3. Go to 'keyma.sh'
4. Click '>>START TYPING NOW!' (Doesn't matter whether you're signed in or not)
5. Wait for the countdown to finish
6. Observe everything on-screen disappearing

**Expected behavior**
The Pop-up showing the countdown should disappear and allow me to see everything meant to be on the screen and start typing.

**Screenshots**
![Screenshot 2021-04-27 at 2 13 38 PM - Display 2](https://user-images.githubusercontent.com/65630426/116313713-f5f46400-a762-11eb-958f-ef3ceac80528.png)
![Screenshot 2021-04-27 at 2 13 31 PM - Display 2](https://user-images.githubusercontent.com/65630426/116313749-04428000-a763-11eb-829f-d966294a643a.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS [e.g. iOS]
 - Browser: Google Chrome [e.g. chrome, safari]
 - Version 76.0.3809.136 (Official Build) (64-bit)

**Additional context**
I am on a school Chromebook which has some features limited but not many and I don't see how any of them would cause this problem. I am using an ad-blocker in the screenshots, but the glitch still occurs when it is turned off and still occurs when I have all chrome extensions disabled, so it isn't a problem with my widgets.

**Comment by CameronCT** [comment]
Have you tried the following here:
https://keyma.sh/about/troubleshooting

Specifically 
1. Clear your cache
2. Delete your cookies
3. Disable Tampermonkey/Greasemonkey scripts
4. Disable "Dark Reader" extensions

Usually this problem occurs if you have Dark Reader enabled.

**Comment by atome1ectron** [comment]
Yessir, I cleared all my cache and my cookies and disabled all scripts/extensions, even reset my chrome browser theme. Still doesn't work

**Comment by CameronCT** [comment]
Have you tried just playing as Guest and seeing if that issue persists? If you are, then it has to be cache-related. Make sure when you clear your cache, you're clearing from "the beginning of time" and not "last hour" or whatever.

**Comment by atome1ectron** [comment]
I have but just to make sure I tried to do that again. I tried playing on guest after clearing my entire history and cache for all time, while all of my chrome extensions/scripts are disabled, and it's still happening, sadly.

**Comment by CameronCT** [comment]
Can you screenshot the steps you are taking to clear your cache/cookies? I have asked a few Chromebook users and they said they are not experiencing any issues. Thanks!

**Comment by atome1ectron** [comment]
**Clearing The Cache and History:**
![Screenshot 2021-05-02 at 12 45 49 PM](https://user-images.githubusercontent.com/65630426/116825601-d71c1600-ab44-11eb-8b9b-8ebb8b25522b.png)
^ This is where I start. [1]

![Screenshot 2021-05-02 at 12 46 15 PM](https://user-images.githubusercontent.com/65630426/116825599-d6837f80-ab44-11eb-8c49-c3f9c4528e56.png)
^ I click on the three dots, hover my mouse over "History", then hover over "History" in the second pop-up (ignore some of the weird tabs in my history lol)

![Screenshot 2021-05-02 at 12 46 34 PM](https://user-images.githubusercontent.com/65630426/116825597-d5eae900-ab44-11eb-9ecd-4d4f2bbd10ca.png)
^ After clicking on "History" in the second pop-up, it opens a new tab. I move my mouse over to "Clear Browsing Data"

![Screenshot 2021-05-02 at 12 46 46 PM](https://user-images.githubusercontent.com/65630426/116825596-d5525280-ab44-11eb-93d2-7f5809798cdc.png)
^ Clicking on "Clear Browsing Data" opens up the Chrome OS Settings and automatically opens up to the pop-up with the header "Clear Browsing Data"

![Screenshot 2021-05-02 at 12 46 54 PM](https://user-images.githubusercontent.com/65630426/116825595-d4212580-ab44-11eb-947d-6169d501ee39.png)
^ This is me clicking on "Clear Data" (you can tell because the button is a lighter blue than in the previous screenshot)

![Screenshot 2021-05-02 at 12 47 08 PM](https://user-images.githubusercontent.com/65630426/116825594-d2eff880-ab44-11eb-8f1e-f0278ad3e0ad.png)
^ Second pop-up telling me that it successfully cleared the Chrome data

![Screenshot 2021-05-02 at 1 00 36 PM](https://user-images.githubusercontent.com/65630426/116825948-6f66ca80-ab46-11eb-93d5-61293a01dccd.png)
^ After clicking out of the pop-up, I return to the "History" Chrome tab and it shows that all my browsing history has been cleared (This was taken after I'd already started writing this post)

I also got signed out of Github (took all the screenshots prior to realizing) and had to sign in again to write and upload all the screenshots.

**Trying to Use Keyma.sh:**
![Screenshot 2021-05-02 at 1 07 49 PM](https://user-images.githubusercontent.com/65630426/116826163-835efc00-ab47-11eb-94ee-7010b69637d4.png)
^ I open a new tab and manually type in keyma.sh [2] [3]

![Screenshot 2021-05-02 at 1 07 57 PM](https://user-images.githubusercontent.com/65630426/116826291-2879d480-ab48-11eb-82c1-21aada7390a7.png)
^ I click on ">> Start Typing Now!", the page briefly changes to the "Play" tab of the website before quickly joining a race.

![Screenshot 2021-05-02 at 1 08 05 PM](https://user-images.githubusercontent.com/65630426/116826377-89091180-ab48-11eb-8686-5468807dab9e.png)
^ After the timer counts all the way down (reaching 0), all the elements on the screen seem to disappear. Refreshing just brings me back to the main page

**Finishing Thoughts:**
One weird part of the problem is that I am able to use to "Learn" section of the website but that also does have some random glitches/problems and inconsistencies. 

No other website (typing or not) seems to have this problem, so idk what the problem is lol, I hope my in-depth thing helps.

 -------------------------------------------------------------------------------------------------------------------------------------
1: I am using two monitors and the notification at the bottom right is just indicating that I used a keyboard shortcut to change my monitor settings from "Extending the display" to "Mirroring the display" so it would be easier to take/organize screenshots. The same problem with the screen disappearing happens whether or not I have a second monitor plugged in at all.

2: Note that I am using a guest account because clearing the history and cache signed me out of my keyma.sh account.

3: I started to take the screenshots of keyma.sh after I'd completely written the "**Clearing The Cache and History**" section

**Comment by CameronCT** [comment]
Thank you for this, I'm truthfully at a loss for what it could be. Keeping this issue open as it is a bug. If you open "Inspect Element" and select the "Network" does it show anything meaningful? 

Also, do you have Discord - would help to jump into a call to see if we can replicate this better.

**Comment by atome1ectron** [comment]
I checked "Network" in inspect element but nothing seemed to show up. 
Yee, my discord is atom#0267

**Comment by CameronCT** [comment]
Closing since issue is resolved.
