### ISSUE TITLE
Run out of time to complete the match when type over 350+ WPM

### ISSUE THREAD

**Issue by DorisCarson** [Keyma-sh/game-tracker#70]
**Describe the bug**
>You have run out of time to complete the match. Better luck next time!

No way, why does it timeout when i'm typing at 366 WPM?
escription of what you expected to happen.

## Screenshot
![timeout](https://user-images.githubusercontent.com/84324561/126070368-e0440e5a-2389-41e7-9f5b-c3328fcf8c2d.png)

 - OS: Artix Linux runit
 - Browser Librewolf 
 - Version 89.0.2 x64

**Comment by CameronCT** [comment]
Very pointless report.
