### ISSUE TITLE
Global Chat "Online Now" shows someone is online, even though they aren't

### ISSUE THREAD

**Issue by cyan-amethyst** [Keyma-sh/game-tracker#74]
**Describe the bug**
Title. 

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser:  Opera GX
 - Version:  LVL 3 (core: 77.0.4054.275)

**Additional context**
Another person sees this same issue, so it's not something that's only happening to me/on my browser.

**Comment by CameronCT** [comment]
Is there any relevant evidence that supports this? The socket removes people on disconnection from the page, and the numbers on the site don't look too far off from what analytics can show.

**Comment by CameronCT** [comment]
After investigating I realized there's a minor issue where when a player disconnects that it does remove them from the global chat however does not re-update the list of players for the rest.

This will be resolved in v2.
