### ISSUE TITLE
Shop items not ordered correctly

### ISSUE THREAD

**Issue by ocdy1001** [Keyma-sh/game-tracker#75]
**Describe the bug**
Shop items are ordered from cheapest to most expensive.
In the Shop/Playercards/Patterns tab there are items of different costs and they are all ordered by prices except one item: "KEYBOARD CHICLETS" which is priced at 7500 but placed among 6500 priced items. This is the only item that is out of order.

**To Reproduce**
1. Go to Shop
2. Click on Playercards tab
3. Click on Patterns subtab
4. Scroll down to the "KEYBOARD CHICLETS" item
5. It's price is 7500 and the surrounding items are priced 6500

**Expected behavior**
Expected "KEYBOARD CHICLETS" to come after "BLACK GRADIENT SPLATTER", being grouped among other 7500 priced items.

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser Firefox
 - Version 90.0.2

**Comment by CameronCT** [comment]
Will be fixed next update. (not v2 update)
