### ISSUE TITLE
Achievements obtained during a game is not translated accurately.

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#76]
![image](https://user-images.githubusercontent.com/1338129/126880099-60a03ae9-24a8-45d6-bc30-6fe6e71ce836.png)

**Comment by popey456963** [comment]
About page too
![image](https://user-images.githubusercontent.com/1338129/126881050-af8ae81d-1740-4e2f-a219-270cf275ab05.png)

**Comment by CameronCT** [comment]
Fixed next update.
