### ISSUE TITLE
Spanish quotes in Casual

### ISSUE THREAD

**Issue by DefinitelyNotJah** [Keyma-sh/game-tracker#78]
Somehow a Spanish quote sneaked its' way in Casual/Regular.
Unfortunately I did not go through with it or I would have submitted more information.

**To Reproduce**
I guess it's a matter of chance at this point.
Try and retry until you stumble upon this quote.

**Expected behavior**
The Casual/Regular section is English-only, quotes that are not English should not be allowed.

**Screenshots**
![2021-07-25_23-49](https://user-images.githubusercontent.com/63221794/126986866-a508f6d9-5bb7-417a-af3a-579c402b777f.png)

**Desktop (please complete the following information):**
 - OS: POPOS 21.04
 - Browser: Vivaldi
 - Version: 4

**Additional context**
I (JUNGKOOK-2428) found it around 25/07/2021 23:49-23:50 UTC+1, hope this is useful.

**Comment by CameronCT** [comment]
Fixed, also searched through and placed every spanish text into spanish locale. (at least hopefully)
