### ISSUE TITLE
Leave button in customs

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#8]
With the removal of the leave back to lobby button, public customs are now a lot harder for me to use. It's frustrating to play a custom game without communication with the host. A lot of the times I don't feel like typing a text and I just want the host to end. However, because they're nice, they wait for me to finish before ending the game.

Solution: add back the leave button in customs and make it "disqualify" the player  and automatically make them finish the match.

No alternatives yet, but I'm sure there's a better way to add the leave button functionality back.

**Comment by CameronCT** [comment]
I've neglected this issue because I don't think this feature is necessarily useful - the lobby owner should be able to control the whole lobby.

I'm going to close this for now, if someone else has an opinion on this then I am open and will re-open the issue.
