### ISSUE TITLE
Visual bug: caret will deviate during browser zooming/scaling

### ISSUE THREAD

**Issue by DefinitelyNotJah** [Keyma-sh/game-tracker#81]
**Describe the bug**
The caret/word pointer will deviate to the next letter/word/right when zooming in.

**To Reproduce**
Simply start a match, type a little bit, stop then zoom in.

**Expected behavior**
The caret must stay fixed in its' place when zooming in.

**Screenshots**
![2021-07-28_21-34](https://user-images.githubusercontent.com/63221794/127392043-003f67b3-efce-440b-b5b1-2292fc4f4b69.png)
https://user-images.githubusercontent.com/63221794/127391911-dc5fd612-6e03-414d-b1f3-f57422e2ed0f.mp4

**Desktop (please complete the following information):**
 - OS: POP OS 21.04
 - Browser : Vivaldi
 - Version : 4
 - Screen resolution : 1366 × 768

**Comment by CameronCT** [comment]
You're not supposed to resize your browser while playing the game. I'm not going to add a script that is constantly cycling through client code to make sure the caret is always perfect.

The only appropriate bug for this caret right now, is the height doesn't scale properly so I will leave this open for that.

**Comment by CameronCT** [comment]
I realized that there is an event listener called `resize` that allows me to check for resizing of the browser.

The bug where the height doesn't scale will be fixed in v2, additionally resizing will also fix the cursor.
