### ISSUE TITLE
Custom lobbies 1v1s not showing correct opponents

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#82]
1v1s in custom lobbies often do not show the correct opponent and just choose someone else from the lobby. Sometimes it will display your name and one random player or duplicates one random player for both sides. This seems to happen randomly, as sometimes it's working just fine. This visual bug both occurs on the player and spectator side.

**To Reproduce**
1. Be in a lobby with more than two players
2. Start an unranked 1v1

![Screenshot_84](https://user-images.githubusercontent.com/85042709/127399739-eb0eb877-f1ac-4f96-b807-c9de062ff1f1.png)

**Comment by CameronCT** [comment]
This has been fixed in v2
