### ISSUE TITLE
Fixing the Guest spam issue

### ISSUE THREAD

**Issue by vainlol** [Keyma-sh/game-tracker#83]
Sometimes when guests join they aren't very nice people and spam. Mostly doesn't happen in the Keyma.sh community and the rare times when there's an unpleasant experience there's a guest involved. My suggestion would be to include a spam detection system, cooldown system, or the ability to kick guests, because once they're in the best course is to start a new lobby.

**Comment by CameronCT** [comment]
Actual lobby features is something I've been wanting to add for a while now, additionally I am starting to consider adding some "measure" where Guests are just disallowed to speak in lobbies in general.

**Comment by CameronCT** [comment]
Also, if a Guest is potentially breaking rules with pure harassment then our Admin/mods can actually ban them from playing :)

**Comment by CameronCT** [comment]
To update this issue, I am currently in the process of adding the following.

- Lobby Owner reassignment on disconnect (done)
- Banning players from Lobbies (90% done, need to do design)
- Giving ownership to other players (90% done, need to do design)

**Comment by CameronCT** [comment]
Lobby moderation has now been added to v2.
