### ISSUE TITLE
Player card `RED SPLATTER` has the wrong price.

### ISSUE THREAD

**Issue by ocdy1001** [Keyma-sh/game-tracker#84]
**Describe the bug**
The player card `RED SPLATTER` seems to have the wrong price. It's priced at 5000 coins. This makes it out of order(comes after `BLUE LEAVES` which is priced at 6000 coins and before card `BLUE SPLATTER` which is priced at 6500.
The are many splatter variants and they are all priced at 6500 coins so `RED SPLATTER` probably should be priced consistently.

**To Reproduce**
1. Go to Shop/Playercards/patterns
2. Scroll down to find card `RED SPLATTER`
3. Observe it's price and the priced of the previous and next items as well as the prices of all the platter cards. 

**Expected behavior**
`RED SPLATTER` is expected to be priced at 6500 coins.

**Screenshots**
![2021-08-01-164204_1198x738_scrot](https://user-images.githubusercontent.com/14070776/127775001-7b840e0d-84a6-4a41-ad03-692fdc2679ca.png)

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser Firefox
 - Version 90.0.2

**Comment by CameronCT** [comment]
Opened a new issue here: https://github.com/Keyma-sh/items/issues/7
