### ISSUE TITLE
Learning center 'Introduction to Numbers' texts go off screen.

### ISSUE THREAD

**Issue by ocdy1001** [Keyma-sh/game-tracker#85]
**Describe the bug**
The number is just one 'word' without any spaces in it so it won't wrap. This makes is so that if the string does not fit on your screen, they just go offscreen and you can't see them. I need to play fullscreen for `PI to 70 CHARACTERS` and above because they won't fit on half a screen. 

**To Reproduce**
1. Use a sufficiently small window size
2. Go to Learn -> Introduction to numbers -> PI TO 90 CHARACTERS (for example)
3. Click on it to stars.
4. Observe the text going offscreen and it won't wrap.

**Expected behavior**
Maybe a special wrapping behavior can be introduced for this lesson as it's quite different from any other texts on keymash. Normally a bunch of words can be wrapped but here it's just one word. Maybe just put in some space in between the numbers.

**Screenshots**
![2021-08-01-212050_1208x362_scrot](https://user-images.githubusercontent.com/14070776/127782878-a7eb4750-b123-4559-a468-17ff31cb9f04.png)

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser Firefox
 - Version 90.0.2

**Comment by CameronCT** [comment]
Fixed in v2
