### ISSUE TITLE
Players with long names can bug layout on ranked

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#87]
**Describe the bug**
DefinitelyNotJah gets shortened to DefinitelyNotJa..., a name which appears to be long enough to sometimes bug the player card:
![image](https://user-images.githubusercontent.com/1338129/128270013-a9362d6e-42fd-4363-9703-0fe4f057d3fa.png)

This in turn makes the entire screen jump up and down if you're on a monitor large enough to fit in all on one screen (e.g. 1440p @ 160% zoom).  This makes ranked much harder, as the text constantly jumps up and down a couple of times a second.

**To Reproduce**
Play against someone with a long name, have them type.

**Expected behavior**
Screen doesn't bounce around.

**Screenshots**
![image](https://user-images.githubusercontent.com/1338129/128270017-9401f04e-7008-48e6-b410-8965268be7b8.png)

**Comment by CameronCT** [comment]
Looks like we need to truncate an extra character. The issue with name truncating is that each letter can sometimes be a different width so flexbox doesn't respect that fully.

**Comment by CameronCT** [comment]
Fixed in v2. The playercard styling is similar between Free for All and 1v1 Duel Mode now. However it will still remain on opposite sides of each other.
