### ISSUE TITLE
Daily average ladder

### ISSUE THREAD

**Issue by nathannguyen650** [Keyma-sh/game-tracker#89]
**Is your feature request related to a problem? Please describe.**
I don't really enjoy the top-speed ladders.  It just proves that you can burst.  It also promotes a burst-and-pray strategy.  I really only joined the tournament because I like the 20-average format due to the emphasis on consistency.  I was thinking perhaps you can alternate between top-speed ladders and 10-race average ladders.  

**Describe the solution you'd like**
a 10-race average daily ladder on even or odd-numbered days.

**Comment by popey456963** [comment]
Would love this as well!

**Comment by CameronCT** [comment]
Months ago we did used to do a "endurance" ladder however we removed it because after 7 days there was literally <5 people using it. I'd be happy to re-introduce an Average WPM or Endurance however I'd like more feedback on this from others.

**Comment by popey456963** [comment]
Izzy + myself seem to be pro this.

**Comment by aevi72** [comment]
Good idea if the average WPM would be calculated from only 3 to 5 games max, anything more than that would be too much to ask from players.

**Comment by nathannguyen650** [comment]
How about a **weekly** average ladder that runs concurrently alongside the top-speed daily ladder?  It'd be kinda like a mini tourney every week

**Comment by nathannguyen650** [comment]
> Months ago we did used to do a "endurance" ladder however we removed it because after 7 days there was literally <5 people using it. I'd be happy to re-introduce an Average WPM or Endurance however I'd like more feedback on this from others.

How about a weekly average ladder that runs concurrently alongside the top-speed daily ladder? It'd be kinda like a mini tourney every week

**Comment by CameronCT** [comment]
To update this, in v2 I have created the ability to set the Average WPM counter to be other numbers other than 20. Therefore the future of this is now even more possible.

We will be doing some testing in v2 in the nearest future with this.

**Comment by CameronCT** [comment]
Closing this issue as we will be starting implementation into v2 as of today.
