### ISSUE TITLE
Ranked queue should search 'faster' if there have been fewer players in the last x minutes.

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#91]
**Is your feature request related to a problem? Please describe.**
Quite often there seems to only be one or two people in the queue at a time.  If one of them is ranked and the other is unranked, it seems to take ~2 minutes of waiting for them to queue up.  This quickly gets annoying.

**Describe the solution you'd like**
Keep a counter of the number of people in ranked.  If it falls below a certain threshold double / triple the expansion rate for searching for players further away from your elo.

**Describe alternatives you've considered**
Get more players on ranked, but posting "Come fight me bro" in Discord hasn't been effective.

**Additional context**
None.

**Comment by CameronCT** [comment]
We actually already have a system like this, after 10 seconds it will increase your ranked multiplier. The issue with increasing it more, is matches can be a little weird in terms of how uneven the games are. That problem already exists now, so for now I can't really do much, it's all player-based problems.
