### ISSUE TITLE
"Recent matches" on one's profile rarely showing 0th as the match placement.

### ISSUE THREAD

**Issue by aevi72** [Keyma-sh/game-tracker#92]
**Describe the bug**
Rarely, after completing a match, the placement for that match shows as "0th" on the "Recent Matches" page on a player's profile

The match still counts for EXP and coins, but according to another player, doesn't count to a player's wins.

**To Reproduce**
I don't know how to reproduce the issue since it happens very rarely and randomly.

**Expected behavior**
It should display the correct placement for the match.

**Screenshots**

![image](https://user-images.githubusercontent.com/85042709/128435036-47cc4f77-ff94-4fd8-8ba9-dba6ea54601f.png)

**Comment by ocdy1001** [comment]
I just has that too. The only other player did quit (bar became red before they typed anything). I finished the match but got "0th". It counts towards the players loss since I was not awarded a win but `casual_won + casual_lost = casual_played`, for me its `5650 + 842 = 6492`.

**Comment by CameronCT** [comment]
Yeah, I'm not fully too sure how it is recreated. It is potentially created when a player leaves and then when the match ends the placement updates don't correlate. Tagged v2 since this will be included in the rewrite

**Comment by CameronCT** [comment]
This has been patched in v2 thanks to @Aevi and @cyamethyst
