### ISSUE TITLE
Hovering over 'words per minute' score should give precise score.

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#93]
**Is your feature request related to a problem? Please describe.**
No way to see precise score from 'match completed' screen

**Describe the solution you'd like**
When hovering over the WPM, it brings up the exact value, Monkeytype style:

![image](https://user-images.githubusercontent.com/1338129/129761065-8ea82085-c9cf-4ce9-b081-4b2b75ad1dfd.png)

**Describe alternatives you've considered**
Going back to leaderboard and seeing it there only works if you're got a high typing speed.

**Comment by CameronCT** [comment]
Due to the nature of `react-countup` I cannot append a tooltip to it as easily.  Therefore it will now just show the default score by default.
