### ISSUE TITLE
Competition results should give more coins

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#96]
**Is your feature request related to a problem? Please describe.**
At the moment, the daily rewards give a very small amount of coins, ranging from the results of one match (250 coins) to 5 matches (1250 coins).  It feels like if you win a competetion then it should result in more coins than you can earn in ~180 seconds.

**Describe the solution you'd like**
Higher prizes in competition games.

**Describe alternatives you've considered**
Decrease prizes in non-competition games.

**Additional context**
Plausible this is from my own bias.

**Comment by CameronCT** [comment]
Added in v2.
