### ISSUE TITLE
"Damn" shouldn't be a censored word.

### ISSUE THREAD

**Issue by popey456963** [Keyma-sh/game-tracker#97]

**Comment by popey456963** [comment]
![image](https://user-images.githubusercontent.com/1338129/130370071-ece97073-768e-4d65-b556-5180b58f051e.png)

**Comment by popey456963** [comment]
![image](https://user-images.githubusercontent.com/1338129/130370109-38c154b1-f887-4f61-bba9-c63efa7300a8.png)

**Comment by popey456963** [comment]
![image](https://user-images.githubusercontent.com/1338129/130370330-0c160b00-9389-4cce-ac8a-3673d4576386.png)

Ah crap, but then he pointed out a valid reason for it to be banned:

![image](https://user-images.githubusercontent.com/1338129/130370334-6e4aa503-b096-4a9c-b6f8-9ae35ad266cb.png)

**Comment by CameronCT** [comment]
Follow format please.
