### ISSUE TITLE
Discord Bot: Can't handle spaces

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#98]
**Describe the bug**
The discord bot that shows player stats cannot handle spaces in names properly

**To Reproduce**
Go to #bot-commands
Use k!user "Blank blank-2333"
Returns improperly formatted

**Expected behavior**
Quotation marks should pass insides as a single parameter.

**Comment by CameronCT** [comment]
More appropriate bug report for:

https://github.com/keyma-sh/discord
