### ISSUE TITLE
Keymash Safari Browser Bug

### ISSUE THREAD

**Issue by SomethingTerrible666** [Keyma-sh/game-tracker#99]
https://youtu.be/6vbuLTfe5RI
I uploaded a short vid of the bug.
Because it gives me both the accent and the letter with the accent (ig. é) I have to delete the accent and then go to the front of the word in order to type it. This only seems to happen on the Safari browser but I haven't tested anything besides chrome and brave.[https://youtu.be/6vbuLTfe5RI](url)

**Comment by CameronCT** [comment]
Likely related to this: https://github.com/Keyma-sh/game-tracker/issues/80
